
PROJECT_NAME := open-co2-monitor
CFLAGS := -DSNTP_GET_SERVERS_FROM_DHCP=1  -DLWIP_DHCP_GET_NTP_SRV=1
CXXFLAGS := -fno-rtti -DSNTP_GET_SERVERS_FROM_DHCP=1 -DLWIP_DHCP_GET_NTP_SRV=1

include $(IDF_PATH)/make/project.mk
