name: Build 
on:
  push:
    tags:
      - 'v*'
jobs:
  build-esp8266:
    runs-on: ubuntu-latest
    steps:
    - name: Install zip
      run: sudo apt-get install -y zip
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Copy SDK Config
      run: |
        pwd
        cp boards/esp8266-rtossdk/* .        
    - uses: airmeter-io/esp8266-rtos-sdk@v3
  # build-esp32:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Install zip
  #     run: sudo apt-get install -y zip
  #   - name: Checkout repo
  #     uses: actions/checkout@v2
  #     with:
  #       submodules: 'recursive'
  #   - name: Copy SDK Config
  #     run: |
  #       pwd
  #       cp boards/esp32-idf/* .
  #   - name: esp-idf build
  #     uses: espressif/esp-idf-ci-action@release-v4.3
  #     with:
  #       path: '.'

  #   - name: Build Artifacts
  #     run: |
  #       export
  #       chmod a+x boards/esp32-idf/buildzipdir.sh
  #       boards/esp32-idf/buildzipdir.sh

  #   - uses: ncipollo/release-action@v1
  #     with:
  #       artifacts: "/tmp/build/*.zip"
  #       bodyFile: "CHANGELOG.md"
  #       token: ${{ secrets.GITHUB_TOKEN }}
    






    