name: Build ESP32
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install zip
      run: sudo apt-get install -y zip
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Copy SDK Config
      run: |
        pwd
        cp boards/esp32-idf/* .
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@release-v4.3
      with:
        path: '.'

    - name: Build Artifacts
      run: |
        pwd
        export
        chmod a+x boards/esp32-idf/buildzipdir.sh
        boards/esp32-idf/buildzipdir.sh
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: ESP32Binaries-{{github.ref}}
        path: /tmp/build/esp32zip/
        retention-days: 5
        






    