name: Build 
on:
  push:
    tags:
      - 'v*'
jobs:
  # build-esp8266:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Install zip
  #     run: sudo apt-get install -y zip
  #   - name: Checkout repo
  #     uses: actions/checkout@v2
  #     with:
  #       submodules: 'recursive'
  #   - name: Copy SDK Config
  #     run: |
  #       pwd
  #       cp boards/esp8266-rtossdk/* .        
  #   - uses: airmeter-io/esp8266-rtos-sdk@v3
  build-esp32:
    runs-on: ubuntu-latest
    steps:
    - name: Install zip
      run: sudo apt-get install -y zip
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Copy SDK Config
      run: |
        echo ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        pwd
        cp boards/esp32-idf/* .
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@release-v4.3
      with:
        path: '.'

    - name: Build Artifacts
      run: |
        export
        chmod a+x boards/esp32-idf/buildzipdir.sh
        boards/esp32-idf/buildzipdir.sh

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "/tmp/build/*.zip"
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#*/})"
      id: extract_branch        
    - uses: julb/action-post-twitter-status@v1
      with:
        message: "${{ steps.extract_branch.outputs.branch }} is now available for download at https://github.com/airmeter-io/AirMeter.IO.Firmware/releases/tag/${{ steps.extract_branch.outputs.branch }}"
        twitter_app_consumer_api_key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        twitter_app_consumer_api_secret_key: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        twitter_app_access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        twitter_app_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    






    